### PR TITLE
Hide the Trigger Build button on the pull request UI page because it doesn't work.

### PR DESCRIPTION
**Pull request by jimCresswell**

### CODE REVIEW

**Comment by jimCresswell** [comment]
@triblondon you're going to make me late :smile:

**Comment by matthew-andrews** [comment]
Was this suggested solution to the "Trigger Build button not working" problem communicated with the rest of the team?  None of myself, @georgecrawford or @rowanbeentje knew anything about this idea and it isn't really a fix...

We've worked around the problem of this button not working via pushing empty commits but it's far from ideal and hiding the button doesn't really achieve anything...  I thought that with part of the money they saved by moving us to Stash would be spent on fixing it so that it supported our workflow better :-(

**Comment by triblondon** [comment]
I didn't understand all the ins and outs of this situation so I wrote this and discussed it with Jim:

https://docs.google.com/a/ft.com/document/d/1N1yWy7-S_2xAsPloZdbGnhI5OY3rQeC5lCkOoCoCC04/edit

If it's causing pain in the development process, we should address it, but I thought Jim was saying that it wasn't, so we should clarify this.

**Comment by triblondon** [comment]
Button now works anyway.

**Pull request closed without merging**
